### ISSUE TITLE
preserveNewLinesBetweenPropertyValues option seems ignored by vscode extension

### ISSUE THREAD

**Issue by fabien-michel** [ThisIsManta/stylus-supremacy#109]
Reproduce:
Have VS code with `thisismanta.stylus-supremacy` extension installed

Create two files in an empty folder:
`./.vscode/settings.json`

```json
{
    "stylusSupremacy.preserveNewLinesBetweenPropertyValues": true
}
```

`./test.stylus`

```
.blop
    background: linear-gradient(to right, blue, red), 
                blue
```

Try to format the stylus file using the extension, you get:
```css
.blop {
    background: linear-gradient(to right, blue, red), blue;
}
```

which is not expected, because of `preserveNewLinesBetweenPropertyValues` set to true.

It works as expected from command line :

`stylus-supremacy format test.stylus --options .vscode/settings.json`

Results:
```css
.blop {
	background:
		linear-gradient(to right, blue, red),
		blue;
}
```
