### ISSUE TITLE
Error formatting because of uneven braces

### ISSUE THREAD

**Issue by LightGlobal** [ThisIsManta/stylus-supremacy#17]
sorry, my english is poor

I use vscode plugin vscode-stylus-supremacy to format my css code, but it throw warning `unexpected "}" `

```css
.modal{
  .modal-img {
    size: 210
  }

  .modal-line
    width: rem(212)
    border: 1px solid #dfdfdf
}
```

expect format to

```css
.modal{
  .modal-img {
    size: 210
  }

  .modal-line{
    width: rem(212)
    border: 1px solid #dfdfdf
  }
}
```

my  vscode-stylus-supremacy config
```json
{
"[stylus]": {
    "editor.formatOnSave": true
  },
  "languageStylus.useSeparator": true,
  "stylusSupremacy.insertColons": true,
  "stylusSupremacy.insertSemicolons": false,
  "stylusSupremacy.insertBraces": true,
  "stylusSupremacy.insertNewLineAroundImports": true,
  "stylusSupremacy.insertNewLineAroundBlocks": "nested",
  "stylusSupremacy.insertNewLineAroundProperties": false,
  "stylusSupremacy.insertNewLineAroundOthers": false,
  "stylusSupremacy.insertNewLineBetweenSelectors": true,
  "stylusSupremacy.insertSpaceBeforeComment": true,
  "stylusSupremacy.insertSpaceAfterComment": true,
  "stylusSupremacy.insertSpaceAfterComma": true,
  "stylusSupremacy.insertSpaceInsideParenthesis": false,
  "stylusSupremacy.insertParenthesisAfterNegation": false,
  "stylusSupremacy.insertParenthesisAroundIfCondition": true,
  "stylusSupremacy.insertNewLineBeforeElse": false,
  "stylusSupremacy.insertLeadingZeroBeforeFraction": true,
  "stylusSupremacy.quoteChar": "'",
  "stylusSupremacy.sortProperties": false,
  "stylusSupremacy.alwaysUseImport": false,
  "stylusSupremacy.alwaysUseNot": false,
  "stylusSupremacy.alwaysUseAtBlock": false,
  "stylusSupremacy.alwaysUseExtends": false,
  "stylusSupremacy.alwaysUseNoneOverZero": false,
  "stylusSupremacy.alwaysUseZeroWithoutUnit": true,
  "stylusSupremacy.reduceMarginAndPaddingValues": false
}
```
